---
name: lab1 
vmm_pod:
    server: q-pod13-vmm.englab.juniper.net
    user: <username>
    password: <password>
    image:
        centos: centos300g.img
        ubuntu: ubuntu160406.img
        vmx_re: vmx-19.3R1.8/junos-vmx-x86-64-19.3R1.8.vmdk
        vmx_mpc: vmx-19.3R1.8/vFPC-20190819.vmdk
        vqfx_re: vqfx/jinstall-vqfx-10-f-17.3R3-S2.2.vmdk
        vqfx_cosim: vqfx/cosim-2018-02-12.vmdk
    junos_login:
        login: admin
        password: pass01
vm:
    gw:
        type: gw
        os: centos
        interfaces:
          em0: external
          em1: [lan0,172.16.10.1/24]
          em2: [lan1,172.16.11.1/24]
          em3: [lan2,172.16.12.1/24]
          em4: [lan3,172.16.13.1/24]
          em5: [lan4,172.16.14.1/24]
    node0:
        type: pcbig
        os: ubuntu
        interfaces:
          em0: [lan0,172.16.10.10/24,172.16.10.1]
    node1:
        type: pcbig
        os: ubuntu
        interfaces:
          em0: [lan1,172.16.11.10/24,172.16.11.1]
    node2:
        type: pcbig
        os: ubuntu
        interfaces:
          em0: [lan2,172.16.12.10/24,172.16.12.1]
    node3:
        type: pcbig
        os: ubuntu
        interfaces:
          em0: [lan3,172.16.13.10/24,172.16.14.1]
    node4:
        type: pcbig
        os: ubuntu
        interfaces:
          em0: [lan4,172.16.14.10/24,172.16.14.1]
